### PR TITLE
C-005 Cleanup (Reorder perms and classes)

### PR DESCRIPTION
**Pull request by freedom1b2830**
I decided to start clearing the warnings, even though they are not significant

Signed-off-by: freedom1b2830 <freedom1b2830@gmail.com>

### CODE REVIEW

**Comment by pebenito** [comment]
Did you use sediff to verify there were no changes in the final policy?

**Comment by freedom1b2830** [comment]
I didn't know about checking with sediff.
launched it with old and new policy.33, no output.
What arguments should I run sediff with?

**Comment by pebenito** [comment]
> I didn't know about checking with sediff. launched it with old and new policy.33, no output. What arguments should I run sediff with?

No output means there are no changes.

**Comment by pebenito** [comment]
It took some time, but I manually reviewed all the changes and it look good.

I've added sediff to the GitHub checks; would you please rebase your change to `main` so it will run the new checks? I'd like extra confirmation since the checks run in multiple combinations of the build options.

**Pull request closed without merging**
