### PR TITLE
Improve a previous syslog tunable policy change

### PR DESCRIPTION
**Pull request by gtrentalancia**
Improve a previous syslog tunable policy change.

### CODE REVIEW

**Comment by dsugar100** [comment]
Silly question - is it worth splitting this (and maybe the similar syslog tunable) into two?  outbound network vs. inbound network?  So one could enable policy for audit or syslog to only send syslog/audit off box, but not receive.  Or to receive only but not send off box?  Maybe it will make for too many tunables, but just thinking about how these types of things are typically used.  In or out.

**Comment by gtrentalancia** [comment]
Receiving logs from remote machines is not dangerous for the machine that receives them (server), as the data that transits over the network can only disclose information of remote machines (clients).

It's the responsibility of the client machines to disable networking on their end !

So, I believe splitting in two gives no benefit.

**Comment by gtrentalancia** [comment]
In my opinion, the issue with adding too many booleans is not much related to the increased number of them, but instead related to the policy becoming more difficult to configure, as it would take much more time for system administrators to understand how to properly use them.

**Comment by dsugar100** [comment]
Sounds good, I agree, I'm not sure it is worth it.  Just a thought I had when I saw your merge request.

**Comment by pebenito** [comment]
The explicit purpose of `audisp-remote` is to log to a remote server. I disagree with this change.

**Review by pebenito — APPROVED** [review]

**Pull request merged**
