### PR TITLE
samba and ntp fixes

### PR DESCRIPTION
**Pull request by yizhao1**

### CODE REVIEW

**Comment by pebenito** [comment]
What fails when `net_admin` is denied on samba?

**Comment by yizhao1** [comment]
This avc message only happens on systemd-based system but not on sysvinit-based system. And seems it doesn't  impact the smb/nmb daemon running.

**Comment by yizhao1** [comment]
> What fails when `net_admin` is denied on samba?

This avc message only happens on systemd-based system but not on sysvinit-based system. And seems it doesn't impact the smb/nmb daemon running.

**Review by pebenito — CHANGES_REQUESTED** [review]
Please change the samba `net_admin` to dontaudits.

**Review by pebenito — APPROVED** [review]

**Pull request merged**
